### ISSUE TITLE
Shahar Garin - day07

### ISSUE THREAD

**Issue by ShaharGarin** [szabgab/wis-python-course-2024-04#180]
Hello.

[My assignment is done](https://github.com/ShaharGarin/shahar_assignments/blob/main/day07/fetch_proteins.py).

Thank you.

**Comment by szabgab** [comment]
There should be a `requirements.txt` file.

This should not give me an exception:

```
$ python fetch_proteins.py 
Traceback (most recent call last):
  File "/home/gabor/Weizmann-2024-04/Shahar-Garin/day07/fetch_proteins.py", line 45, in <module>
    main()
  File "/home/gabor/Weizmann-2024-04/Shahar-Garin/day07/fetch_proteins.py", line 11, in main
    search = search_protein()
             ^^^^^^^^^^^^^^^^
  File "/home/gabor/Weizmann-2024-04/Shahar-Garin/day07/fetch_proteins.py", line 19, in search_protein
    raise Exception("Please provide search term and numberof files to download")
Exception: Please provide search term and numberof files to download
```

When I run
```
python fetch_proteins.py cat 3
```

I get:

```
	cat sequence WP_348520844.1
	cat sequence WP_348521818.1
	cat sequence XBK71260.1
	protein search log.csv
```

It would be better if the filenames did not have space in them (use _ instead) and if they had an extension reflecting the filetype.

**Comment by ShaharGarin** [comment]
Made all fixes suggested.

**Comment by szabgab** [comment]
ok
