### ISSUE TITLE
day09 Assignment - Shaked Levy

### ISSUE THREAD

**Issue by LevyShaked** [szabgab/wis-python-course-2024-04#249]
https://github.com/LevyShaked/Assignments_rep/tree/main/day09

**Comment by szabgab** [comment]
nice, but you get a crash:

```
$ python analyze.py  --letter_duplicate X  ID_NM_001410955.1.data 
letter_duplicate_function: 
Length of the repeted letter sequence = 0
Traceback (most recent call last):
  File "/home/gabor/git/Weizmann-2024-04/Shaked-Levy/day09/analyze.py", line 57, in <module>
    letter_duplicate_function(sequence_file,letter_duplicate)
  File "/home/gabor/git/Weizmann-2024-04/Shaked-Levy/day09/analyze.py", line 49, in letter_duplicate_function
    print(f'Repeted letter sequence part = {word}')
                                            ^^^^
UnboundLocalError: cannot access local variable 'word' where it is not associated with a value
```
