### ISSUE TITLE
final project - TheaM

### ISSUE THREAD

**Issue by theammn** [szabgab/wis-python-course-2024-04#264]
Hi, 
this is the link for my final project repository : https://github.com/theammn/TDP43_project/tree/main

Thank you for the course, it was really interesting and helpful!!
Have a nice week,

Best, 
thea meimoun

**Comment by szabgab** [comment]
If I run the visualization before the identity I get this error:

```
$ python visualization.py 
Traceback (most recent call last):
  File "/home/gabor/git/Weizmann-2024-04/Thea-Meimoun-project/visualization.py", line 38, in <module>
    identity_results = read_identity_scores(file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/git/Weizmann-2024-04/Thea-Meimoun-project/visualization.py", line 6, in read_identity_scores
    with open(file_path, mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'identity_scores.csv'
```


otherwise nice.
